SRC="$SCRIPT_PATH/backup/source"
DST="$SCRIPT_PATH/backup/destination"
REPO="$DST/repo"
MNT="$DST/mnt"
PATTERN="$DST/pattern.conf"
RESTORE="$DST/restore"
LOGPATH="$DST/borg.log"
LISTPATH="$DST/archives.txt"
ARCHIVE="$LABEL-$(date --iso-8601=seconds)"